# Generated by Django 4.2.4 on 2023-08-31 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bolg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("body", models.TextField()),
                ("full_body", models.TextField()),
                ("category", models.CharField(max_length=500)),
                ("name", models.CharField(max_length=256)),
                ("date", models.DateField()),
            ],
        ),
    ]
