# Generated by Django 4.2.4 on 2023-08-31 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_bolg"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Bolg",
        ),
    ]
